python Merge_Sequential_Classification.py 0 2 &
python Merge_Sequential_Classification.py 1 2 &
python Merge_Sequential_Classification.py 2 2 &
python Merge_Sequential_Classification.py 3 2 &
python Merge_Sequential_Classification.py 4 2 &
python Merge_Sequential_Classification.py 5 2 &
python Merge_Sequential_Classification.py 6 2 &
python Merge_Sequential_Classification.py 7 2 &
python Merge_Sequential_Classification.py 8 2 &
python Merge_Sequential_Classification.py 9 2 &
python Merge_Sequential_Classification.py 0 3 &
python Merge_Sequential_Classification.py 1 3 &
python Merge_Sequential_Classification.py 2 3 &
python Merge_Sequential_Classification.py 3 3 &
python Merge_Sequential_Classification.py 4 3 &
python Merge_Sequential_Classification.py 5 3 &
python Merge_Sequential_Classification.py 6 3 &
python Merge_Sequential_Classification.py 7 3 &
python Merge_Sequential_Classification.py 8 3 &
python Merge_Sequential_Classification.py 9 3 &
echo done!
