python Merge_Sequential_Classification.py 0 0 srnc &
python Merge_Sequential_Classification.py 1 0 srnc &
python Merge_Sequential_Classification.py 2 0 srnc &
python Merge_Sequential_Classification.py 3 0 srnc &
python Merge_Sequential_Classification.py 4 0 srnc &
python Merge_Sequential_Classification.py 5 0 srnc &
python Merge_Sequential_Classification.py 6 0 srnc &
python Merge_Sequential_Classification.py 7 0 srnc &
python Merge_Sequential_Classification.py 8 0 srnc &
python Merge_Sequential_Classification.py 9 0 srnc &
python Merge_Sequential_Classification.py 0 0 svm &
python Merge_Sequential_Classification.py 1 0 svm &
python Merge_Sequential_Classification.py 2 0 svm &
python Merge_Sequential_Classification.py 3 0 svm &
python Merge_Sequential_Classification.py 4 0 svm &
python Merge_Sequential_Classification.py 5 0 svm &
python Merge_Sequential_Classification.py 6 0 svm &
python Merge_Sequential_Classification.py 7 0 svm &
python Merge_Sequential_Classification.py 8 0 svm &
python Merge_Sequential_Classification.py 9 0 svm &
python Merge_Sequential_Classification.py 0 0 dt &
python Merge_Sequential_Classification.py 1 0 dt &
python Merge_Sequential_Classification.py 2 0 dt &
python Merge_Sequential_Classification.py 3 0 dt &
python Merge_Sequential_Classification.py 4 0 dt &
python Merge_Sequential_Classification.py 5 0 dt &
python Merge_Sequential_Classification.py 6 0 dt &
python Merge_Sequential_Classification.py 7 0 dt &
python Merge_Sequential_Classification.py 8 0 dt &
python Merge_Sequential_Classification.py 9 0 dt &
python Merge_Sequential_Classification.py 0 0 lr &
python Merge_Sequential_Classification.py 1 0 lr &
python Merge_Sequential_Classification.py 2 0 lr &
python Merge_Sequential_Classification.py 3 0 lr &
python Merge_Sequential_Classification.py 4 0 lr &
python Merge_Sequential_Classification.py 5 0 lr &
python Merge_Sequential_Classification.py 6 0 lr &
python Merge_Sequential_Classification.py 7 0 lr &
python Merge_Sequential_Classification.py 8 0 lr &
python Merge_Sequential_Classification.py 9 0 lr &
python Merge_Sequential_Classification.py 0 1 srnc &
python Merge_Sequential_Classification.py 1 1 srnc &
python Merge_Sequential_Classification.py 2 1 srnc &
python Merge_Sequential_Classification.py 3 1 srnc &
python Merge_Sequential_Classification.py 4 1 srnc &
python Merge_Sequential_Classification.py 5 1 srnc &
python Merge_Sequential_Classification.py 6 1 srnc &
python Merge_Sequential_Classification.py 7 1 srnc &
python Merge_Sequential_Classification.py 8 1 srnc &
python Merge_Sequential_Classification.py 9 1 srnc &
python Merge_Sequential_Classification.py 0 1 svm &
python Merge_Sequential_Classification.py 1 1 svm &
python Merge_Sequential_Classification.py 2 1 svm &
python Merge_Sequential_Classification.py 3 1 svm &
python Merge_Sequential_Classification.py 4 1 svm &
python Merge_Sequential_Classification.py 5 1 svm &
python Merge_Sequential_Classification.py 6 1 svm &
python Merge_Sequential_Classification.py 7 1 svm &
python Merge_Sequential_Classification.py 8 1 svm &
python Merge_Sequential_Classification.py 9 1 svm &
python Merge_Sequential_Classification.py 0 1 dt &
python Merge_Sequential_Classification.py 1 1 dt &
python Merge_Sequential_Classification.py 2 1 dt &
python Merge_Sequential_Classification.py 3 1 dt &
python Merge_Sequential_Classification.py 4 1 dt &
python Merge_Sequential_Classification.py 5 1 dt &
python Merge_Sequential_Classification.py 6 1 dt &
python Merge_Sequential_Classification.py 7 1 dt &
python Merge_Sequential_Classification.py 8 1 dt &
python Merge_Sequential_Classification.py 9 1 dt &
python Merge_Sequential_Classification.py 0 1 lr &
python Merge_Sequential_Classification.py 1 1 lr &
python Merge_Sequential_Classification.py 2 1 lr &
python Merge_Sequential_Classification.py 3 1 lr &
python Merge_Sequential_Classification.py 4 1 lr &
python Merge_Sequential_Classification.py 5 1 lr &
python Merge_Sequential_Classification.py 6 1 lr &
python Merge_Sequential_Classification.py 7 1 lr &
python Merge_Sequential_Classification.py 8 1 lr &
python Merge_Sequential_Classification.py 9 1 lr &
python Merge_Sequential_Classification.py 0 mean srnc &
python Merge_Sequential_Classification.py 1 mean srnc &
python Merge_Sequential_Classification.py 2 mean srnc &
python Merge_Sequential_Classification.py 3 mean srnc &
python Merge_Sequential_Classification.py 4 mean srnc &
python Merge_Sequential_Classification.py 5 mean srnc &
python Merge_Sequential_Classification.py 6 mean srnc &
python Merge_Sequential_Classification.py 7 mean srnc &
python Merge_Sequential_Classification.py 8 mean srnc &
python Merge_Sequential_Classification.py 9 mean srnc &
python Merge_Sequential_Classification.py 0 mean svm &
python Merge_Sequential_Classification.py 1 mean svm &
python Merge_Sequential_Classification.py 2 mean svm &
python Merge_Sequential_Classification.py 3 mean svm &
python Merge_Sequential_Classification.py 4 mean svm &
python Merge_Sequential_Classification.py 5 mean svm &
python Merge_Sequential_Classification.py 6 mean svm &
python Merge_Sequential_Classification.py 7 mean svm &
python Merge_Sequential_Classification.py 8 mean svm &
python Merge_Sequential_Classification.py 9 mean svm &
python Merge_Sequential_Classification.py 0 mean dt &
python Merge_Sequential_Classification.py 1 mean dt &
python Merge_Sequential_Classification.py 2 mean dt &
python Merge_Sequential_Classification.py 3 mean dt &
python Merge_Sequential_Classification.py 4 mean dt &
python Merge_Sequential_Classification.py 5 mean dt &
python Merge_Sequential_Classification.py 6 mean dt &
python Merge_Sequential_Classification.py 7 mean dt &
python Merge_Sequential_Classification.py 8 mean dt &
python Merge_Sequential_Classification.py 9 mean dt &
python Merge_Sequential_Classification.py 0 mean lr &
python Merge_Sequential_Classification.py 1 mean lr &
python Merge_Sequential_Classification.py 2 mean lr &
python Merge_Sequential_Classification.py 3 mean lr &
python Merge_Sequential_Classification.py 4 mean lr &
python Merge_Sequential_Classification.py 5 mean lr &
python Merge_Sequential_Classification.py 6 mean lr &
python Merge_Sequential_Classification.py 7 mean lr &
python Merge_Sequential_Classification.py 8 mean lr &
python Merge_Sequential_Classification.py 9 mean lr &
echo done!
